In [23]:
import pandas as pd
import numpy as np
import gzip


# Import sets

In [6]:
path = "C:/Users/Bruna/OneDrive/Documentos/estudos sobre DNA/"
file = "fullBacteriaP1.txt"
txt1 = pd.read_csv(path+file, sep=',', header=None)
txt1

0
0     0.3211370672670980 0.1298366236446730 0.284628...
1     0.3191806615776080 0.1953689567430030 0.267221...
2     0.3848945828642780 0.1566695557171650 0.163762...
3     0.4206054630864700 0.1566239440159290 0.179222...
4     0.3476212679068120 0.1868820039551750 0.204680...
...                                                 ...
9217  0.2082055436606680 0.2951218100804350 0.252994...
9218  0.1873094834170310 0.3050901299737080 0.279277...
9219  0.1824403786462050 0.3087933062137310 0.269243...
9220  0.1784117779043480 0.3186843059079380 0.257102...
9221  0.1932692984307930 0.3064844134825140 0.266413...

[9222 rows x 1 columns]

In [5]:
path = "C:/Users/Bruna/OneDrive/Documentos/estudos sobre DNA/"
file = "fullBacteriaP2.txt"
txt2 = pd.read_csv(path+file, sep=',', header=None)
txt2

0
0     0.3582422187511900 0.1824005993879130 0.203804...
1     0.3202263750515830 0.2014711758271270 0.252032...
2     0.3902239469763220 0.1697560865763170 0.146903...
3     0.4225163516506150 0.1462738837101510 0.156172...
4     0.3444835136001510 0.1891483460380290 0.202895...
...                                                 ...
9217  0.2176767327758970 0.2771059360099510 0.258102...
9218  0.1776783938299250 0.3253148881288940 0.271782...
9219  0.1844965213904520 0.3219915091336750 0.257123...
9220  0.1807911854506840 0.3389530510199570 0.239284...
9221  0.1824504433778790 0.3328849001730690 0.256802...

[9222 rows x 1 columns]

# organize sets to become dataframes with entries type float64

In [8]:
txt1 = txt1.rename(columns={0:"column"})

column
0     0.3211370672670980 0.1298366236446730 0.284628...
1     0.3191806615776080 0.1953689567430030 0.267221...
2     0.3848945828642780 0.1566695557171650 0.163762...
3     0.4206054630864700 0.1566239440159290 0.179222...
4     0.3476212679068120 0.1868820039551750 0.204680...
...                                                 ...
9217  0.2082055436606680 0.2951218100804350 0.252994...
9218  0.1873094834170310 0.3050901299737080 0.279277...
9219  0.1824403786462050 0.3087933062137310 0.269243...
9220  0.1784117779043480 0.3186843059079380 0.257102...
9221  0.1932692984307930 0.3064844134825140 0.266413...

[9222 rows x 1 columns]

In [9]:
txt2 = txt2.rename(columns={0:"column2"})
txt2

column2
0     0.3582422187511900 0.1824005993879130 0.203804...
1     0.3202263750515830 0.2014711758271270 0.252032...
2     0.3902239469763220 0.1697560865763170 0.146903...
3     0.4225163516506150 0.1462738837101510 0.156172...
4     0.3444835136001510 0.1891483460380290 0.202895...
...                                                 ...
9217  0.2176767327758970 0.2771059360099510 0.258102...
9218  0.1776783938299250 0.3253148881288940 0.271782...
9219  0.1844965213904520 0.3219915091336750 0.257123...
9220  0.1807911854506840 0.3389530510199570 0.239284...
9221  0.1824504433778790 0.3328849001730690 0.256802...

[9222 rows x 1 columns]

In [18]:
df1=txt1.column.str.split(pat=' ',expand=True)

In [19]:
df1

0                   1                   2   \
0     0.3211370672670980  0.1298366236446730  0.2846286840094890   
1     0.3191806615776080  0.1953689567430030  0.2672213740458020   
2     0.3848945828642780  0.1566695557171650  0.1637626728034080   
3     0.4206054630864700  0.1566239440159290  0.1792224864196100   
4     0.3476212679068120  0.1868820039551750  0.2046802900461440   
...                  ...                 ...                 ...   
9217  0.2082055436606680  0.2951218100804350  0.2529946183669930   
9218  0.1873094834170310  0.3050901299737080  0.2792778787858310   
9219  0.1824403786462050  0.3087933062137310  0.2692436715571920   
9220  0.1784117779043480  0.3186843059079380  0.2571022972436530   
9221  0.1932692984307930  0.3064844134825140  0.2664133417774960   

                      3                   4                   5   \
0     0.2643976250787400  0.2867240549644440  0.1834571993797790   
1     0.2182290076335880  0.2579341784799850  0.2205333166801970   
2     0.2946731886151490  0.3433566356822250  0.1896269795107600   
3     0.2435481064779910  0.3928932699136950  0.1960699911757740   
4     0.2608164380918690  0.2764020653552730  0.3261957084918980   
...                  ...                 ...                 ...   
9217  0.2436780278919040  0.1943080216597410  0.2216705344774860   
9218  0.2283225078234300  0.1512518459423220  0.1988949807343030   
9219  0.2395226435828720  0.1559950118545430  0.2038827477907440   
9220  0.2458016189440620  0.1532852053898710  0.1990246777607600   
9221  0.2338329463091970  0.1517701714487550  0.1987050338969000   

                      6                   7                   8   \
0     0.1888894829706460  0.3409292626851311  0.3346065699006880   
1     0.2281521263973020  0.2933803784425150  0.3778246798930630   
2     0.2132219795656330  0.2537944052413820  0.2709627248690960   
3     0.0638787852699998  0.3471579536405310  0.3264885046178030   
4     0.1792803416054740  0.2181218845473550  0.2319668795668870   
...                  ...                 ...                 ...   
9217  0.4365049382049760  0.1475165056577980  0.2258003015754720   
9218  0.5153090149882030  0.1345441583351720  0.2030611791866450   
9219  0.5101706592357671  0.1299515811189460  0.2009964661481740   
9220  0.5269429004112960  0.1207472164380730  0.2031260732366600   
9221  0.5207345950212460  0.1287901996330990  0.2055656612826270   

                      9                   10                  11  \
0     0.2058289591496420  0.2295604458792310  0.2300040250704390   
1     0.1525650766849590  0.2439960602223160  0.2256141831996620   
2     0.2667115972834260  0.1963139613251080  0.2660117165223700   
3     0.1795441147573200  0.1897425820396930  0.3042247985851840   
4     0.2427858671998020  0.3232869199058760  0.2019603333274360   
...                  ...                 ...                 ...   
9217  0.3609373104320850  0.2377073331369050  0.1755550548555380   
9218  0.4145736611106880  0.2281233351092170  0.1542418245934500   
9219  0.4172620109109040  0.2291490004403670  0.1525925225005550   
9220  0.4125956064468950  0.2246978775671820  0.1595804427492640   
9221  0.4087795634663070  0.2250928481235660  0.1605619271274990   

                      12                  13                  14  \
0     0.2196313669869810  0.2077122762730720  0.2189482313292520   
1     0.1339356952260180  0.3134289714934880  0.2392592005495230   
2     0.2319234532999890  0.1616337343204800  0.2202826349830810   
3     0.2655159633610420  0.1271986022131620  0.2088632392651030   
4     0.1980646812586180  0.2042322712748830  0.2556783936193930   
...                  ...                 ...                 ...   
9217  0.1051395618441780  0.3638120151006211  0.3262388157308050   
9218  0.0780544160736710  0.4025650899958140  0.3368003348681460   
9219  0.0786917694715522  0.4000951328791510  0.3402074510525990   
9220  0.0792924880127864  0.4017432072456050  0.3376750133191261   
9221  

In [20]:
df2=txt2.column2.str.split(pat=' ',expand=True)
df2

0                   1                   2   \
0     0.3582422187511900  0.1824005993879130  0.2038045893811830   
1     0.3202263750515830  0.2014711758271270  0.2520322008030550   
2     0.3902239469763220  0.1697560865763170  0.1469035117678190   
3     0.4225163516506150  0.1462738837101510  0.1561724262244420   
4     0.3444835136001510  0.1891483460380290  0.2028951605816560   
...                  ...                 ...                 ...   
9217  0.2176767327758970  0.2771059360099510  0.2581024117199920   
9218  0.1776783938299250  0.3253148881288940  0.2717823021001100   
9219  0.1844965213904520  0.3219915091336750  0.2571236053524700   
9220  0.1807911854506840  0.3389530510199570  0.2392849241116860   
9221  0.1824504433778790  0.3328849001730690  0.2568023266187310   

                      3                   4                   5   \
0     0.2555525924797140  0.2803223871768120  0.2264515227946790   
1     0.2262702483182350  0.2606401755111800  0.2280506644297590   
2     0.2931164546795420  0.3504843764839971  0.1985943584385980   
3     0.2750373384147910  0.4054647962354610  0.1658527923288640   
4     0.2634729797801650  0.2743232754307540  0.3240326807461080   
...                  ...                 ...                 ...   
9217  0.2471149194941610  0.1988074886377850  0.2409623483300670   
9218  0.2252244159410710  0.1572973966272440  0.2277318544135630   
9219  0.2363883641234030  0.1626821271144120  0.2303156639681950   
9220  0.2409708394176730  0.1606199181674530  0.2260671194315670   
9221  0.2278623298303210  0.1558485828265170  0.2241911749816060   

                      6                   7                   8   \
0     0.1442855147596470  0.3489405752688611  0.3414259176221890   
1     0.2092166143498610  0.3020925457092000  0.3756638652869330   
2     0.1998349795802070  0.2510862854971980  0.2708817343471930   
3     0.0594202255171801  0.3692621859184940  0.2944031292254200   
4     0.1781106071792710  0.2235334366438680  0.2255786577677700   
...                  ...                 ...                 ...   
9217  0.4032856606763120  0.1569445023558350  0.2058497484437620   
9218  0.4848322357917060  0.1301385131674870  0.2049968777499360   
9219  0.4803319495521960  0.1266702593651980  0.2010492817716720   
9220  0.4929877251179871  0.1203252372829920  0.2014717025837500   
9221  0.4946860213166649  0.1252742208752120  0.2062552137201000   

                      9                   10                  11  \
0     0.2658702197168660  0.1840475732923370  0.2086562893686080   
1     0.1592312468903910  0.2281652441211520  0.2369396437015240   
2     0.2852806989160330  0.1849603624009060  0.2588772043358680   
3     0.1989569248599580  0.1641636082673360  0.3424763376472860   
4     0.2429836142587540  0.3248758717327740  0.2065618562407020   
...                  ...                 ...                 ...   
9217  0.3700434893834740  0.2317728319263239  0.1923339302464400   
9218  0.4430496797098460  0.1994726511656130  0.1524807913746050   
9219  0.4407424845613490  0.2024218398584140  0.1557863938085650   
9220  0.4382875139983859  0.2003451258793000  0.1598956575385640   
9221  0.4402246432341770  0.1987831824815430  0.1547369605641800   

                      12                  13                  14  \
0     0.2309007718260390  0.2675575568305610  0.1767342977307390   
1     0.1342282096327000  0.3253939752760500  0.2201408637529810   
2     0.2361501609086060  0.1752503768598460  0.2038303536153610   
3     0.2528165884966670  0.1494840780054310  0.1656677363613920   
4     0.1959789866457190  0.2050643165750200  0.2509573841319720   
...                  ...                 ...                 ...   
9217  0.1128124591022120  0.3608820834969240  0.3017275225755790   
9218  0.0763248819893912  0.4344055671808850  0.3070773922494200   
9219  0.0802719042068277  0.4275472218392390  0.3088502563202690   
9220  0.0815908745519072  0.4340622010852561  0.3044617076245050   
9221  

In [57]:
df1 = df1.astype(float)
df2 = df2.astype(float)

# Find pi value for the 1st line

In [192]:
# get 1st line and organize as a 4x4 matrix considering the order we need, which is every 4 elements is a line of the matrix
line1=df1.iloc[:1]
a1 = np.array([[line1[0], line1[1], line1[2], line1[3]],
             [line1[4], line1[5], line1[6], line1[7]],
             [line1[8], line1[9], line1[10], line1[11]],
             [line1[12], line1[13], line1[14], line1[15]]])
matrix1=np.array(a1).reshape(4,4)
matrix1

array([[0.32113707, 0.12983662, 0.28462868, 0.26439763],
       [0.28672405, 0.1834572 , 0.18888948, 0.34092926],
       [0.33460657, 0.20582896, 0.22956045, 0.23000403],
       [0.21963137, 0.20771228, 0.21894823, 0.35370813]])

In [189]:
# transpose the matrix because we need eigenvector from the left
transposta1 = np.transpose(matrix1)
transposta1

array([[0.32113707, 0.28672405, 0.33460657, 0.21963137],
       [0.12983662, 0.1834572 , 0.20582896, 0.20771228],
       [0.28462868, 0.18888948, 0.22956045, 0.21894823],
       [0.26439763, 0.34092926, 0.23000403, 0.35370813]])

In [195]:
b1,r1 = np.linalg.eig(transposta1)
b1

array([ 1.        +0.j        ,  0.14030623+0.j        ,
       -0.0262217 +0.05142939j, -0.0262217 -0.05142939j])

In [196]:
r1[1]

array([-0.35482565+0.j,  0.28174796+0.j, -0.61140075+0.j, -0.61140075-0.j])

# Generalize the method for the rest of the data

In [325]:
# organizing all lines as the matrix needed and store in one table
lenghtdf1 = list(range(1,9222))
lista=[matrix1]
for i in lenghtdf1:
    line=df1.iloc[i:i+1]
    a = np.array([[line[0], line[1], line[2], line[3]],
             [line[4], line[5], line[6], line[7]],
             [line[8], line[9], line[10], line[11]],
             [line[12], line[13], line[14], line[15]]])
    matrix=np.array(a).reshape(4,4)
    lista.append(matrix)

In [326]:
transpostadf1=[]
for n in lista:
    transposta = np.transpose(n)
    transpostadf1.append(transposta)

In [327]:
transpostadf1

[array([[0.32113707, 0.28672405, 0.33460657, 0.21963137],
        [0.12983662, 0.1834572 , 0.20582896, 0.20771228],
        [0.28462868, 0.18888948, 0.22956045, 0.21894823],
        [0.26439763, 0.34092926, 0.23000403, 0.35370813]]),
 array([[0.31918066, 0.25793418, 0.37782468, 0.1339357 ],
        [0.19536896, 0.22053332, 0.15256508, 0.31342897],
        [0.26722137, 0.22815213, 0.24399606, 0.2392592 ],
        [0.21822901, 0.29338038, 0.22561418, 0.31337613]]),
 array([[0.38489458, 0.34335664, 0.27096272, 0.23192345],
        [0.15666956, 0.18962698, 0.2667116 , 0.16163373],
        [0.16376267, 0.21322198, 0.19631396, 0.22028263],
        [0.29467319, 0.25379441, 0.26601172, 0.38616018]]),
 array([[0.42060546, 0.39289327, 0.3264885 , 0.26551596],
        [0.15662394, 0.19606999, 0.17954411, 0.1271986 ],
        [0.17922249, 0.06387879, 0.18974258, 0.20886324],
        [0.24354811, 0.34715795, 0.3042248 , 0.3984222 ]]),
 array([[0.34762127, 0.27640207, 0.23196688, 0.19806468],
      

In [268]:
eingenvaluedf1 = []
eingenvectordf1 = []
for matriz in transpostadf1:
    b,r = np.linalg.eig(matriz)
    eingenvaluedf1.append(b)
    eingenvectordf1.append(r)

In [269]:
# it looks like the eingenvalue 1 is always the first element in the matrix. We need to validate that
eingenvaluedf1

[array([ 1.        +0.j        ,  0.14030623+0.j        ,
        -0.0262217 +0.05142939j, -0.0262217 -0.05142939j]),
 array([ 1.        ,  0.16435974, -0.00513232, -0.06214124]),
 array([ 1.        +0.j        ,  0.10176435+0.05060723j,
         0.10176435-0.05060723j, -0.046533  +0.j        ]),
 array([1.        +0.j        , 0.1569511 +0.j        ,
        0.02394457+0.06291099j, 0.02394457-0.06291099j]),
 array([1.        +0.j        , 0.12002159+0.06664155j,
        0.12002159-0.06664155j, 0.09908537+0.j        ]),
 array([1.        +0.j        , 0.17819104+0.j        ,
        0.02959495+0.03834368j, 0.02959495-0.03834368j]),
 array([ 1.        +0.j        ,  0.06862966+0.06241399j,
         0.06862966-0.06241399j, -0.08693732+0.j        ]),
 array([ 1.        +0.j        ,  0.03744965+0.08714167j,
         0.03744965-0.08714167j, -0.10910603+0.j        ]),
 array([1.        +0.j        , 0.17167797+0.j        ,
        0.05728379+0.03299541j, 0.05728379-0.03299541j]),
 array([1.

In [270]:
# how to access the first element of the second matrix in eingenvaluedf1
primeiro = eingenvaluedf1[1]
primeiro[0].round()

1.0

In [271]:
# getting all the first elements of all matrices and putting them on a table
eingenvalues1 = []
for i in lenghtdf1:
    primeiro = eingenvaluedf1[i]
    valor = primeiro[0].round()
    eingenvalues1.append(valor)

In [272]:
eingenvalues1

[1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 

In [274]:
# this code shows us all the eingenvalues are 1 for the first element of all the matrices, so we can consider the first 
# eingenvalue as the pi we are looking for
for n in eingenvalues1:
    if n != 1:
        print(n)

In [275]:
# table with all the pi functions we where looking for
pidf1 = []
for matriz in eingenvectordf1:
    vetor = matriz[0]
    pidf1.append(vetor)

In [330]:
pidf1

[array([-0.56622126+0.j        , -0.58660633+0.j        ,
        -0.02011774+0.41514231j, -0.02011774-0.41514231j]),
 array([-0.54158835, -0.74801016,  0.43463727,  0.65909332]),
 array([-0.59843436+0.j, -0.74315584+0.j, -0.74315584-0.j,  0.3166523 +0.j]),
 array([ 0.66273506+0.j        , -0.73483674+0.j        ,
        -0.30005764+0.22107639j, -0.30005764-0.22107639j]),
 array([-0.52824879+0.j,  0.53878277+0.j,  0.53878277-0.j,  0.4708294 +0.j]),
 array([0.61623812+0.j        , 0.65331302+0.j        ,
        0.31948237+0.21217812j, 0.31948237-0.21217812j]),
 array([-0.48833289+0.j,  0.6219517 +0.j,  0.6219517 -0.j,  0.16453592+0.j]),
 array([-0.41101266+0.j,  0.66408838+0.j,  0.66408838-0.j,  0.07652858+0.j]),
 array([ 0.59898892+0.j        , -0.78754597+0.j        ,
         0.40081044+0.15791593j,  0.40081044-0.15791593j]),
 array([ 0.58389941+0.j        ,  0.54647727+0.j        ,
        -0.00636557+0.40660077j, -0.00636557-0.40660077j]),
 array([0.59693768, 0.79123279, 0.422703

# is the least DNA a leading strand?

In [256]:
# In order to know if is a leading strand, we need to verify if piG + piT > piA + piC, 
# where pi = [piA piC piG piT] was the eingenvectors found previously

In [332]:
test = pidf1[9221]
GTtest = test[2]+test[3]
ACtest = test[0]+test[1]

if GTtest > ACtest:
    print('It is leading strand!')
else:
    print('It is not leading strand')
# Note that GTtest > ACtest, that means the DNA strand on the position 1 of df1 is the leading strand

It is leading strand!


In [339]:
GTtest

(-0.7709822529099164+0j)

In [340]:
ACtest

(-0.9258488762497219+0j)

# Generalize for all lines and get only the leading strand lines

In [342]:
lenghtdf1 = list(range(1,9222))
classificacaodf1=[]
for i in lenghtdf1:
    matrix = pidf1[i]
    GT = matrix[2]+matrix[3]
    AC = matrix[0]+matrix[1]
    if GT>AC:
        classificacaodf1.append('leading')
    else:
        classificacaodf1.append('no')


    

In [343]:
classificador = pd.DataFrame(classificacaodf1)

In [344]:
df1['is it leading'] = classificador

In [345]:
df1

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading  
0     0.218948  0.353708       leading  
1     0.239259  0.313376       leading  
2     0.220283  0.386160            no  
3     0.208863  0.398422       leading  
4     0.255678  0.342025            no  
...        ...       ...           ...  
9217  0.326239  0.204810       leading  
9218  0.336800  0.182580       leading  
9219  0.340207  0.181006       leading  
9220  0.337675  0.181289       leading  
9221  0.331585  0.185893           NaN  

[9222 rows x 17 columns]

In [346]:
# The least column wasn't classified for some reason
pd.isnull(df1['is it leading']).values.sum()
#was we calculated previously the least line is strand, I'll add thid to the least line

1

In [347]:
df1 = df1.replace(to_replace = np.nan, value ='leading')

In [348]:
# No NaN values anymore!
pd.isnull(df1['is it leading']).values.sum()

0

# The same classification for df2

In [350]:
# get 1st line and organize as a 4x4 matrix considering the order we need, which is every 4 elements is a line of the matrix
line1=df2.iloc[:1]
a1 = np.array([[line1[0], line1[1], line1[2], line1[3]],
             [line1[4], line1[5], line1[6], line1[7]],
             [line1[8], line1[9], line1[10], line1[11]],
             [line1[12], line1[13], line1[14], line1[15]]])
matrix1=np.array(a1).reshape(4,4)
matrix1

array([[0.35824222, 0.1824006 , 0.20380459, 0.25555259],
       [0.28032239, 0.22645152, 0.14428551, 0.34894058],
       [0.34142592, 0.26587022, 0.18404757, 0.20865629],
       [0.23090077, 0.26755756, 0.1767343 , 0.32480737]])

In [352]:
# organizing all lines as the matrix needed and store in one table
lenghtdf1 = list(range(1,9222))
lista=[matrix1]
for i in lenghtdf1:
    line=df2.iloc[i:i+1]
    a = np.array([[line[0], line[1], line[2], line[3]],
             [line[4], line[5], line[6], line[7]],
             [line[8], line[9], line[10], line[11]],
             [line[12], line[13], line[14], line[15]]])
    matrix=np.array(a).reshape(4,4)
    lista.append(matrix)

In [353]:
transpostadf1=[]
for n in lista:
    transposta = np.transpose(n)
    transpostadf1.append(transposta)

In [354]:
eingenvaluedf1 = []
eingenvectordf1 = []
for matriz in transpostadf1:
    b,r = np.linalg.eig(matriz)
    eingenvaluedf1.append(b)
    eingenvectordf1.append(r)

In [362]:
# this code shows us all the eingenvalues are 1 for the first element of all the matrices, so we can consider the first 
# eingenvalue as the pi we are looking for
for n in eingenvalues1:
    if n != 1:
        print(n)

In [361]:
# getting all the first elements of all matrices and putting them on a table
eingenvalues1 = []
for i in lenghtdf1:
    primeiro = eingenvaluedf1[i]
    valor = primeiro[0].round()
    eingenvalues1.append(valor)

In [355]:
# table with all the pi functions we where looking for
pidf1 = []
for matriz in eingenvectordf1:
    vetor = matriz[0]
    pidf1.append(vetor)

In [356]:
lenghtdf1 = list(range(1,9222))
classificacaodf1=[]
for i in lenghtdf1:
    matrix = pidf1[i]
    GT = matrix[2]+matrix[3]
    AC = matrix[0]+matrix[1]
    if GT>AC:
        classificacaodf1.append('leading')
    else:
        classificacaodf1.append('no')

In [357]:
classificador = pd.DataFrame(classificacaodf1)

In [358]:
df2['is it leading'] = classificador

In [359]:
df2

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
2     0.390224  0.169756  0.146904  0.293116  0.350484  0.198594  0.199835   
3     0.422516  0.146274  0.156172  0.275037  0.405465  0.165853  0.059420   
4     0.344484  0.189148  0.202895  0.263473  0.274323  0.324033  0.178111   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.217677  0.277106  0.258102  0.247115  0.198807  0.240962  0.403286   
9218  0.177678  0.325315  0.271782  0.225224  0.157297  0.227732  0.484832   
9219  0.184497  0.321992  0.257124  0.236388  0.162682  0.230316  0.480332   
9220  0.180791  0.338953  0.239285  0.240971  0.160620  0.226067  0.492988   
9221  0.182450  0.332885  0.256802  0.227862  0.155849  0.224191  0.494686   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
2     0.251086  0.270882  0.285281  0.184960  0.258877  0.236150  0.175250   
3     0.369262  0.294403  0.198957  0.164164  0.342476  0.252817  0.149484   
4     0.223533  0.225579  0.242984  0.324876  0.206562  0.195979  0.205064   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.156945  0.205850  0.370043  0.231773  0.192334  0.112812  0.360882   
9218  0.130139  0.204997  0.443050  0.199473  0.152481  0.076325  0.434406   
9219  0.126670  0.201049  0.440742  0.202422  0.155786  0.080272  0.427547   
9220  0.120325  0.201472  0.438288  0.200345  0.159896  0.081591  0.434062   
9221  0.125274  0.206255  0.440225  0.198783  0.154737  0.077122  0.434784   

            14        15 is it leading  
0     0.176734  0.324807       leading  
1     0.220141  0.320237       leading  
2     0.203830  0.384769            no  
3     0.165668  0.432032            no  
4     0.250957  0.347999            no  
...        ...       ...           ...  
9217  0.301728  0.224578       leading  
9218  0.307077  0.182192       leading  
9219  0.308850  0.183331       leading  
9220  0.304462  0.179885       leading  
9221  0.302265  0.185829           NaN  

[9222 rows x 17 columns]

In [360]:
df1

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading  
0     0.218948  0.353708       leading  
1     0.239259  0.313376       leading  
2     0.220283  0.386160            no  
3     0.208863  0.398422       leading  
4     0.255678  0.342025            no  
...        ...       ...           ...  
9217  0.326239  0.204810       leading  
9218  0.336800  0.182580       leading  
9219  0.340207  0.181006       leading  
9220  0.337675  0.181289       leading  
9221  0.331585  0.185893       leading  

[9222 rows x 17 columns]

In [364]:
# Some values went wrong, let us see why
df1['df2 classificator'] = df2['is it leading']

In [365]:
df1

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading df2 classificator  
0     0.218948  0.353708       leading           leading  
1     0.239259  0.313376       leading           leading  
2     0.220283  0.386160            no                no  
3     0.208863  0.398422       leading                no  
4     0.255678  0.342025            no                no  
...        ...       ...           ...               ...  
9217  0.326239  0.204810       leading           leading  
9218  0.336800  0.182580       leading           leading  
9219  0.340207  0.181006       leading           leading  
9220  0.337675  0.181289       leading           leading  
9221  0.331585  0.185893       leading               NaN  

[9222 rows x 18 columns]

In [367]:
df1[(df1['is it leading']=='leading') & (df1['df2 classificator']=='leading')]

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
5     0.399826  0.203989  0.193963  0.202221  0.325573  0.229391  0.171073   
6     0.297059  0.218209  0.214272  0.270461  0.270065  0.221859  0.304784   
10    0.417809  0.124592  0.195595  0.262004  0.296979  0.217540  0.193609   
...        ...       ...       ...       ...       ...       ...       ...   
9215  0.173184  0.322433  0.252421  0.251962  0.162330  0.200504  0.516863   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
5     0.273964  0.271736  0.222691  0.224821  0.280752  0.242408  0.149479   
6     0.203291  0.226893  0.316493  0.238608  0.218006  0.184477  0.226417   
10    0.291872  0.267715  0.288390  0.241864  0.202030  0.223577  0.160273   
...        ...       ...       ...       ...       ...       ...       ...   
9215  0.120303  0.203428  0.413638  0.225276  0.157658  0.075424  0.404830   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   

            14        15 is it leading df2 classificator  
0     0.218948  0.353708       leading           leading  
1     0.239259  0.313376       leading           leading  
5     0.224771  0.383342       leading           leading  
6     0.296310  0.292796       leading           leading  
10    0.194567  0.421583       leading           leading  
...        ...       ...           ...               ...  
9215  0.348620  0.171126       leading           leading  
9217  0.326239  0.204810       leading           leading  
9218  0.336800  0.182580       leading           leading  
9219  0.340207  0.181006       leading           leading  
9220  0.337675  0.181289       leading           leading  

[3677 rows x 18 columns]

In [368]:
df1[(df1['is it leading']=='no') & (df1['df2 classificator']=='no')]

0         1         2         3         4         5         6  \
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
8     0.416845  0.124374  0.194637  0.264145  0.301473  0.214080  0.186119   
12    0.442911  0.098024  0.194793  0.264272  0.434731  0.129947  0.106320   
14    0.444733  0.096759  0.185900  0.272609  0.415038  0.144464  0.106572   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.460966  0.084138  0.200000  0.254897  0.503439  0.126547  0.063274   
9184  0.422332  0.095618  0.183542  0.298508  0.413517  0.151354  0.027141   
9185  0.506972  0.067729  0.181275  0.244024  0.479042  0.095808  0.041916   
9199  0.364897  0.160133  0.201246  0.273723  0.344409  0.172515  0.199096   
9202  0.428969  0.082770  0.208516  0.279745  0.551537  0.104882  0.090416   

             7         8         9        10        11        12        13  \
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
8     0.298328  0.273015  0.288232  0.235089  0.203664  0.222961  0.162274   
12    0.329002  0.414270  0.166727  0.175464  0.243538  0.352892  0.082019   
14    0.333925  0.401214  0.160030  0.181267  0.257490  0.348162  0.088972   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.306740  0.521947  0.129290  0.150838  0.197925  0.423199  0.076121   
9184  0.407988  0.418421  0.144343  0.183777  0.253460  0.332822  0.122222   
9185  0.383234  0.531977  0.122093  0.119186  0.226744  0.388982  0.068447   
9199  0.283980  0.259712  0.275930  0.194840  0.269518  0.282956  0.133052   
9202  0.253165  0.458569  0.145951  0.156309  0.239171  0.409409  0.083280   

            14        15 is it leading df2 classificator  
2     0.220283  0.386160            no                no  
4     0.255678  0.342025            no                no  
8     0.194534  0.420232            no                no  
12    0.177497  0.387592            no                no  
14    0.173977  0.388889            no                no  
...        ...       ...           ...               ...  
9181  0.133213  0.367467            no                no  
9184  0.160284  0.384672            no                no  
9185  0.190317  0.352254            no                no  
9199  0.235922  0.348070            no                no  
9202  0.204704  0.302606            no                no  

[2353 rows x 18 columns]

In [372]:
erro=3677+2353
erro

6030

In [373]:
9222-erro

3192