In [1]:
import pandas as pd
import numpy as np
import gzip

# Import sets

In [2]:
path = "C:/Users/Bruna/OneDrive/Documentos/estudos sobre DNA/"
file = "fullBacteriaP1.txt"
txt1 = pd.read_csv(path+file, sep=',', header=None)
txt1

0
0     0.3211370672670980 0.1298366236446730 0.284628...
1     0.3191806615776080 0.1953689567430030 0.267221...
2     0.3848945828642780 0.1566695557171650 0.163762...
3     0.4206054630864700 0.1566239440159290 0.179222...
4     0.3476212679068120 0.1868820039551750 0.204680...
...                                                 ...
9217  0.2082055436606680 0.2951218100804350 0.252994...
9218  0.1873094834170310 0.3050901299737080 0.279277...
9219  0.1824403786462050 0.3087933062137310 0.269243...
9220  0.1784117779043480 0.3186843059079380 0.257102...
9221  0.1932692984307930 0.3064844134825140 0.266413...

[9222 rows x 1 columns]

In [3]:
path = "C:/Users/Bruna/OneDrive/Documentos/estudos sobre DNA/"
file = "fullBacteriaP2.txt"
txt2 = pd.read_csv(path+file, sep=',', header=None)
txt2

0
0     0.3582422187511900 0.1824005993879130 0.203804...
1     0.3202263750515830 0.2014711758271270 0.252032...
2     0.3902239469763220 0.1697560865763170 0.146903...
3     0.4225163516506150 0.1462738837101510 0.156172...
4     0.3444835136001510 0.1891483460380290 0.202895...
...                                                 ...
9217  0.2176767327758970 0.2771059360099510 0.258102...
9218  0.1776783938299250 0.3253148881288940 0.271782...
9219  0.1844965213904520 0.3219915091336750 0.257123...
9220  0.1807911854506840 0.3389530510199570 0.239284...
9221  0.1824504433778790 0.3328849001730690 0.256802...

[9222 rows x 1 columns]

# organize sets to become dataframes with entries type float64

In [4]:
txt1 = txt1.rename(columns={0:"column"})

In [5]:
txt2 = txt2.rename(columns={0:"column2"})
txt2

column2
0     0.3582422187511900 0.1824005993879130 0.203804...
1     0.3202263750515830 0.2014711758271270 0.252032...
2     0.3902239469763220 0.1697560865763170 0.146903...
3     0.4225163516506150 0.1462738837101510 0.156172...
4     0.3444835136001510 0.1891483460380290 0.202895...
...                                                 ...
9217  0.2176767327758970 0.2771059360099510 0.258102...
9218  0.1776783938299250 0.3253148881288940 0.271782...
9219  0.1844965213904520 0.3219915091336750 0.257123...
9220  0.1807911854506840 0.3389530510199570 0.239284...
9221  0.1824504433778790 0.3328849001730690 0.256802...

[9222 rows x 1 columns]

In [6]:
df1=txt1.column.str.split(pat=' ',expand=True)

In [7]:
df2=txt2.column2.str.split(pat=' ',expand=True)
df2

0                   1                   2   \
0     0.3582422187511900  0.1824005993879130  0.2038045893811830   
1     0.3202263750515830  0.2014711758271270  0.2520322008030550   
2     0.3902239469763220  0.1697560865763170  0.1469035117678190   
3     0.4225163516506150  0.1462738837101510  0.1561724262244420   
4     0.3444835136001510  0.1891483460380290  0.2028951605816560   
...                  ...                 ...                 ...   
9217  0.2176767327758970  0.2771059360099510  0.2581024117199920   
9218  0.1776783938299250  0.3253148881288940  0.2717823021001100   
9219  0.1844965213904520  0.3219915091336750  0.2571236053524700   
9220  0.1807911854506840  0.3389530510199570  0.2392849241116860   
9221  0.1824504433778790  0.3328849001730690  0.2568023266187310   

                      3                   4                   5   \
0     0.2555525924797140  0.2803223871768120  0.2264515227946790   
1     0.2262702483182350  0.2606401755111800  0.2280506644297590   
2     0.2931164546795420  0.3504843764839971  0.1985943584385980   
3     0.2750373384147910  0.4054647962354610  0.1658527923288640   
4     0.2634729797801650  0.2743232754307540  0.3240326807461080   
...                  ...                 ...                 ...   
9217  0.2471149194941610  0.1988074886377850  0.2409623483300670   
9218  0.2252244159410710  0.1572973966272440  0.2277318544135630   
9219  0.2363883641234030  0.1626821271144120  0.2303156639681950   
9220  0.2409708394176730  0.1606199181674530  0.2260671194315670   
9221  0.2278623298303210  0.1558485828265170  0.2241911749816060   

                      6                   7                   8   \
0     0.1442855147596470  0.3489405752688611  0.3414259176221890   
1     0.2092166143498610  0.3020925457092000  0.3756638652869330   
2     0.1998349795802070  0.2510862854971980  0.2708817343471930   
3     0.0594202255171801  0.3692621859184940  0.2944031292254200   
4     0.1781106071792710  0.2235334366438680  0.2255786577677700   
...                  ...                 ...                 ...   
9217  0.4032856606763120  0.1569445023558350  0.2058497484437620   
9218  0.4848322357917060  0.1301385131674870  0.2049968777499360   
9219  0.4803319495521960  0.1266702593651980  0.2010492817716720   
9220  0.4929877251179871  0.1203252372829920  0.2014717025837500   
9221  0.4946860213166649  0.1252742208752120  0.2062552137201000   

                      9                   10                  11  \
0     0.2658702197168660  0.1840475732923370  0.2086562893686080   
1     0.1592312468903910  0.2281652441211520  0.2369396437015240   
2     0.2852806989160330  0.1849603624009060  0.2588772043358680   
3     0.1989569248599580  0.1641636082673360  0.3424763376472860   
4     0.2429836142587540  0.3248758717327740  0.2065618562407020   
...                  ...                 ...                 ...   
9217  0.3700434893834740  0.2317728319263239  0.1923339302464400   
9218  0.4430496797098460  0.1994726511656130  0.1524807913746050   
9219  0.4407424845613490  0.2024218398584140  0.1557863938085650   
9220  0.4382875139983859  0.2003451258793000  0.1598956575385640   
9221  0.4402246432341770  0.1987831824815430  0.1547369605641800   

                      12                  13                  14  \
0     0.2309007718260390  0.2675575568305610  0.1767342977307390   
1     0.1342282096327000  0.3253939752760500  0.2201408637529810   
2     0.2361501609086060  0.1752503768598460  0.2038303536153610   
3     0.2528165884966670  0.1494840780054310  0.1656677363613920   
4     0.1959789866457190  0.2050643165750200  0.2509573841319720   
...                  ...                 ...                 ...   
9217  0.1128124591022120  0.3608820834969240  0.3017275225755790   
9218  0.0763248819893912  0.4344055671808850  0.3070773922494200   
9219  0.0802719042068277  0.4275472218392390  0.3088502563202690   
9220  0.0815908745519072  0.4340622010852561  0.3044617076245050   
9221  

In [8]:
df1 = df1.astype(float)
df2 = df2.astype(float)

In [9]:
df1.to_csv('P1_inicial_organizada.csv')

In [10]:
df2.to_csv('P2_inicial_organizada.csv')

# Find pi value for the 1st line

In [11]:
# get 1st line and organize as a 4x4 matrix considering the order we need, which is every 4 elements is a line of the matrix
line1=df1.iloc[:1]
a1 = np.array([[line1[0], line1[1], line1[2], line1[3]],
             [line1[4], line1[5], line1[6], line1[7]],
             [line1[8], line1[9], line1[10], line1[11]],
             [line1[12], line1[13], line1[14], line1[15]]])
matrix1=np.array(a1).reshape(4,4)
matrix1

array([[0.32113707, 0.12983662, 0.28462868, 0.26439763],
       [0.28672405, 0.1834572 , 0.18888948, 0.34092926],
       [0.33460657, 0.20582896, 0.22956045, 0.23000403],
       [0.21963137, 0.20771228, 0.21894823, 0.35370813]])

In [12]:
# transpose the matrix because we need eigenvector from the left
transposta1 = np.transpose(matrix1)
transposta1

array([[0.32113707, 0.28672405, 0.33460657, 0.21963137],
       [0.12983662, 0.1834572 , 0.20582896, 0.20771228],
       [0.28462868, 0.18888948, 0.22956045, 0.21894823],
       [0.26439763, 0.34092926, 0.23000403, 0.35370813]])

In [13]:
b1,r1 = np.linalg.eig(transposta1)
b1

array([ 1.        +0.j        ,  0.14030623+0.j        ,
       -0.0262217 +0.05142939j, -0.0262217 -0.05142939j])

In [14]:
r1

array([[-0.56622126+0.j        , -0.58660633+0.j        ,
        -0.02011774+0.41514231j, -0.02011774-0.41514231j],
       [-0.35482565+0.j        ,  0.28174796+0.j        ,
        -0.61140075+0.j        , -0.61140075-0.j        ],
       [-0.46191449+0.j        , -0.36237262+0.j        ,
         0.19342944-0.47018564j,  0.19342944+0.47018564j],
       [-0.58320429+0.j        ,  0.66723098+0.j        ,
         0.43808905+0.05504333j,  0.43808905-0.05504333j]])

In [15]:
b1[0]

(0.9999999999999999+0j)

In [16]:
r1[:,0]

array([-0.56622126+0.j, -0.35482565+0.j, -0.46191449+0.j, -0.58320429+0.j])

In [17]:
norms = np.linalg.norm(r1[:,0])

In [18]:
normal=r1[:,0]/(r1[0,0]+r1[1,0]+r1[2,0]+r1[3,0])
normal

array([0.28798248-0.j, 0.18046579-0.j, 0.23493162-0.j, 0.29662011-0.j])

# Generalize the method for the rest of the data

In [19]:
# organizing all lines as the matrix needed and store in one table
lenghtdf1 = list(range(1,9222))
lista=[matrix1]
for i in lenghtdf1:
    line=df1.iloc[i:i+1]
    a = np.array([[line[0], line[1], line[2], line[3]],
             [line[4], line[5], line[6], line[7]],
             [line[8], line[9], line[10], line[11]],
             [line[12], line[13], line[14], line[15]]])
    matrix=np.array(a).reshape(4,4)
    lista.append(matrix)

In [20]:
transpostadf1=[]
for n in lista:
    transposta = np.transpose(n)
    transpostadf1.append(transposta)

In [21]:
transpostadf1

[array([[0.32113707, 0.28672405, 0.33460657, 0.21963137],
        [0.12983662, 0.1834572 , 0.20582896, 0.20771228],
        [0.28462868, 0.18888948, 0.22956045, 0.21894823],
        [0.26439763, 0.34092926, 0.23000403, 0.35370813]]),
 array([[0.31918066, 0.25793418, 0.37782468, 0.1339357 ],
        [0.19536896, 0.22053332, 0.15256508, 0.31342897],
        [0.26722137, 0.22815213, 0.24399606, 0.2392592 ],
        [0.21822901, 0.29338038, 0.22561418, 0.31337613]]),
 array([[0.38489458, 0.34335664, 0.27096272, 0.23192345],
        [0.15666956, 0.18962698, 0.2667116 , 0.16163373],
        [0.16376267, 0.21322198, 0.19631396, 0.22028263],
        [0.29467319, 0.25379441, 0.26601172, 0.38616018]]),
 array([[0.42060546, 0.39289327, 0.3264885 , 0.26551596],
        [0.15662394, 0.19606999, 0.17954411, 0.1271986 ],
        [0.17922249, 0.06387879, 0.18974258, 0.20886324],
        [0.24354811, 0.34715795, 0.3042248 , 0.3984222 ]]),
 array([[0.34762127, 0.27640207, 0.23196688, 0.19806468],
      

In [22]:
eingenvaluedf1 = []
eingenvectordf1 = []
for matriz in transpostadf1:
    b,r = np.linalg.eig(matriz)
    eingenvaluedf1.append(b)
    eingenvectordf1.append(r)

In [23]:
# it looks like the eingenvalue 1 is always the first element in the matrix. We need to validate that
eingenvaluedf1

[array([ 1.        +0.j        ,  0.14030623+0.j        ,
        -0.0262217 +0.05142939j, -0.0262217 -0.05142939j]),
 array([ 1.        ,  0.16435974, -0.00513232, -0.06214124]),
 array([ 1.        +0.j        ,  0.10176435+0.05060723j,
         0.10176435-0.05060723j, -0.046533  +0.j        ]),
 array([1.        +0.j        , 0.1569511 +0.j        ,
        0.02394457+0.06291099j, 0.02394457-0.06291099j]),
 array([1.        +0.j        , 0.12002159+0.06664155j,
        0.12002159-0.06664155j, 0.09908537+0.j        ]),
 array([1.        +0.j        , 0.17819104+0.j        ,
        0.02959495+0.03834368j, 0.02959495-0.03834368j]),
 array([ 1.        +0.j        ,  0.06862966+0.06241399j,
         0.06862966-0.06241399j, -0.08693732+0.j        ]),
 array([ 1.        +0.j        ,  0.03744965+0.08714167j,
         0.03744965-0.08714167j, -0.10910603+0.j        ]),
 array([1.        +0.j        , 0.17167797+0.j        ,
        0.05728379+0.03299541j, 0.05728379-0.03299541j]),
 array([1.

In [24]:
# how to access the first element of the second matrix in eingenvaluedf1
primeiro = eingenvaluedf1[1]
primeiro[0].round()

1.0

In [25]:
# getting all the first elements of all matrices and putting them on a table
eingenvalues1 = []
for i in lenghtdf1:
    primeiro = eingenvaluedf1[i]
    valor = primeiro[0].round()
    eingenvalues1.append(valor)

In [26]:
eingenvalues1

[1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 1.0,
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 (1+0j),
 

In [27]:
# this code shows us all the eingenvalues are 1 for the first element of all the matrices, so we can consider the first 
# eingenvalue as the pi we are looking for
for n in eingenvalues1:
    if n != 1:
        print(n)

In [28]:
# table with all the pi functions we where looking for
pidf1 = []
for matriz in eingenvectordf1:
    vetor = matriz[:,0]/(matriz[0,0]+matriz[1,0]+matriz[2,0]+matriz[3,0])
    pidf1.append(vetor)

In [29]:
pidf1

[array([0.28798248-0.j, 0.18046579-0.j, 0.23493162-0.j, 0.29662011-0.j]),
 array([0.27157408, 0.22130704, 0.2455581 , 0.26156078]),
 array([0.30735233-0.j, 0.1860024 -0.j, 0.19687887-0.j, 0.30976639-0.j]),
 array([0.35041689+0.j, 0.15737058+0.j, 0.17236461+0.j, 0.31984792+0.j]),
 array([0.26438985-0.j, 0.2379263 -0.j, 0.24026164-0.j, 0.25742222-0.j]),
 array([0.31429439+0.j, 0.19735379+0.j, 0.20450097+0.j, 0.28385086+0.j]),
 array([0.24428127-0.j, 0.24699198-0.j, 0.26317678-0.j, 0.24554998-0.j]),
 array([0.2084121 -0.j, 0.29226258-0.j, 0.29211173-0.j, 0.20721359-0.j]),
 array([0.30715234+0.j, 0.18558512+0.j, 0.20116179+0.j, 0.30610074+0.j]),
 array([0.29451787+0.j, 0.21457854+0.j, 0.22157966+0.j, 0.26932393+0.j]),
 array([0.30562885, 0.18621488, 0.20436871, 0.30378757]),
 array([0.29070124-0.j, 0.18474351-0.j, 0.22290076-0.j, 0.30165448-0.j]),
 array([0.40948398-0.j, 0.10873352-0.j, 0.17648147-0.j, 0.30530104-0.j]),
 array([0.40542491+0.j, 0.10861008+0.j, 0.17147687+0.j, 0.31448813+0.j

# is the least DNA a leading strand?

In [30]:
# In order to know if is a leading strand, we need to verify if piG + piT > piA + piC, 
# where pi = [piA piC piG piT] was the eingenvectors found previously

In [31]:
test = pidf1[9221]
GTtest = test[2]+test[3]
ACtest = test[0]+test[1]

if GTtest > ACtest:
    print('It is leading strand!')
else:
    print('It is not leading strand')
# Note that GTtest > ACtest, that means the DNA strand on the position 1 of df1 is the leading strand

It is leading strand!


In [32]:
GTtest

(0.5117665145336614-0j)

In [33]:
ACtest

(0.4882334854663387-0j)

# Generalize for all lines and get only the leading strand lines

In [34]:
lenghtdf1 = list(range(1,9222))
classificacaodf1=[]
for i in lenghtdf1:
    matrix = pidf1[i]
    GT = matrix[2]+matrix[3]
    AC = matrix[0]+matrix[1]
    if GT>AC:
        classificacaodf1.append('leading')
    else:
        classificacaodf1.append('no')


    

In [35]:
classificador = pd.DataFrame(classificacaodf1)

In [36]:
df1['is it leading'] = classificador

In [37]:
df1

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading  
0     0.218948  0.353708       leading  
1     0.239259  0.313376       leading  
2     0.220283  0.386160            no  
3     0.208863  0.398422            no  
4     0.255678  0.342025            no  
...        ...       ...           ...  
9217  0.326239  0.204810       leading  
9218  0.336800  0.182580       leading  
9219  0.340207  0.181006       leading  
9220  0.337675  0.181289       leading  
9221  0.331585  0.185893           NaN  

[9222 rows x 17 columns]

In [38]:
# The least column wasn't classified for some reason
pd.isnull(df1['is it leading']).values.sum()
#was we calculated previously the least line is strand, I'll add thid to the least line

1

In [39]:
df1 = df1.replace(to_replace = np.nan, value ='leading')

In [40]:
# No NaN values anymore!
pd.isnull(df1['is it leading']).values.sum()

0

# The same classification for df2

In [41]:
# get 1st line and organize as a 4x4 matrix considering the order we need, which is every 4 elements is a line of the matrix
line1=df2.iloc[:1]
a1 = np.array([[line1[0], line1[1], line1[2], line1[3]],
             [line1[4], line1[5], line1[6], line1[7]],
             [line1[8], line1[9], line1[10], line1[11]],
             [line1[12], line1[13], line1[14], line1[15]]])
matrix1=np.array(a1).reshape(4,4)
matrix1

array([[0.35824222, 0.1824006 , 0.20380459, 0.25555259],
       [0.28032239, 0.22645152, 0.14428551, 0.34894058],
       [0.34142592, 0.26587022, 0.18404757, 0.20865629],
       [0.23090077, 0.26755756, 0.1767343 , 0.32480737]])

In [42]:
# organizing all lines as the matrix needed and store in one table
lenghtdf1 = list(range(1,9222))
lista=[matrix1]
for i in lenghtdf1:
    line=df2.iloc[i:i+1]
    a = np.array([[line[0], line[1], line[2], line[3]],
             [line[4], line[5], line[6], line[7]],
             [line[8], line[9], line[10], line[11]],
             [line[12], line[13], line[14], line[15]]])
    matrix=np.array(a).reshape(4,4)
    lista.append(matrix)

In [43]:
transpostadf1=[]
for n in lista:
    transposta = np.transpose(n)
    transpostadf1.append(transposta)

In [44]:
eingenvaluedf1 = []
eingenvectordf1 = []
for matriz in transpostadf1:
    b,r = np.linalg.eig(matriz)
    eingenvaluedf1.append(b)
    eingenvectordf1.append(r)

In [45]:
# this code shows us all the eingenvalues are 1 for the first element of all the matrices, so we can consider the first 
# eingenvalue as the pi we are looking for
for n in eingenvalues1:
    if n != 1:
        print(n)

In [46]:
# getting all the first elements of all matrices and putting them on a table
eingenvalues1 = []
for i in lenghtdf1:
    primeiro = eingenvaluedf1[i]
    valor = primeiro[0].round()
    eingenvalues1.append(valor)

In [47]:
pidf1 = []
for matriz in eingenvectordf1:
    vetor = matriz[:,0]/(matriz[0,0]+matriz[1,0]+matriz[2,0]+matriz[3,0])
    pidf1.append(vetor)

In [48]:
lenghtdf1 = list(range(1,9222))
classificacaodf1=[]
for i in lenghtdf1:
    matrix = pidf1[i]
    GT = matrix[2]+matrix[3]
    AC = matrix[0]+matrix[1]
    if GT>AC:
        classificacaodf1.append('leading')
    else:
        classificacaodf1.append('no')

In [49]:
classificador = pd.DataFrame(classificacaodf1)

In [50]:
df2['is it leading'] = classificador

In [51]:
df2

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
2     0.390224  0.169756  0.146904  0.293116  0.350484  0.198594  0.199835   
3     0.422516  0.146274  0.156172  0.275037  0.405465  0.165853  0.059420   
4     0.344484  0.189148  0.202895  0.263473  0.274323  0.324033  0.178111   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.217677  0.277106  0.258102  0.247115  0.198807  0.240962  0.403286   
9218  0.177678  0.325315  0.271782  0.225224  0.157297  0.227732  0.484832   
9219  0.184497  0.321992  0.257124  0.236388  0.162682  0.230316  0.480332   
9220  0.180791  0.338953  0.239285  0.240971  0.160620  0.226067  0.492988   
9221  0.182450  0.332885  0.256802  0.227862  0.155849  0.224191  0.494686   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
2     0.251086  0.270882  0.285281  0.184960  0.258877  0.236150  0.175250   
3     0.369262  0.294403  0.198957  0.164164  0.342476  0.252817  0.149484   
4     0.223533  0.225579  0.242984  0.324876  0.206562  0.195979  0.205064   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.156945  0.205850  0.370043  0.231773  0.192334  0.112812  0.360882   
9218  0.130139  0.204997  0.443050  0.199473  0.152481  0.076325  0.434406   
9219  0.126670  0.201049  0.440742  0.202422  0.155786  0.080272  0.427547   
9220  0.120325  0.201472  0.438288  0.200345  0.159896  0.081591  0.434062   
9221  0.125274  0.206255  0.440225  0.198783  0.154737  0.077122  0.434784   

            14        15 is it leading  
0     0.176734  0.324807            no  
1     0.220141  0.320237            no  
2     0.203830  0.384769       leading  
3     0.165668  0.432032       leading  
4     0.250957  0.347999       leading  
...        ...       ...           ...  
9217  0.301728  0.224578            no  
9218  0.307077  0.182192            no  
9219  0.308850  0.183331            no  
9220  0.304462  0.179885            no  
9221  0.302265  0.185829           NaN  

[9222 rows x 17 columns]

In [54]:
df1.to_csv('df1_cLassificada.csv')

In [56]:
# the least one is NaN but I've checked, is not leading
df2 = df2.replace(to_replace = np.nan, value ='no')

In [57]:
df2.to_csv('df2_cLassificada.csv')

In [105]:
df1

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading df2 classificator  
0     0.218948  0.353708       leading                no  
1     0.239259  0.313376       leading                no  
2     0.220283  0.386160            no           leading  
3     0.208863  0.398422            no           leading  
4     0.255678  0.342025            no           leading  
...        ...       ...           ...               ...  
9217  0.326239  0.204810       leading                no  
9218  0.336800  0.182580       leading                no  
9219  0.340207  0.181006       leading                no  
9220  0.337675  0.181289       leading                no  
9221  0.331585  0.185893       leading               NaN  

[9222 rows x 18 columns]

In [106]:
# Some values went wrong, let us see why
df1['df2 classificator'] = df2['is it leading']

In [118]:
df2['df1 classificator'] = df1['is it leading']
df2

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
2     0.390224  0.169756  0.146904  0.293116  0.350484  0.198594  0.199835   
3     0.422516  0.146274  0.156172  0.275037  0.405465  0.165853  0.059420   
4     0.344484  0.189148  0.202895  0.263473  0.274323  0.324033  0.178111   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.217677  0.277106  0.258102  0.247115  0.198807  0.240962  0.403286   
9218  0.177678  0.325315  0.271782  0.225224  0.157297  0.227732  0.484832   
9219  0.184497  0.321992  0.257124  0.236388  0.162682  0.230316  0.480332   
9220  0.180791  0.338953  0.239285  0.240971  0.160620  0.226067  0.492988   
9221  0.182450  0.332885  0.256802  0.227862  0.155849  0.224191  0.494686   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
2     0.251086  0.270882  0.285281  0.184960  0.258877  0.236150  0.175250   
3     0.369262  0.294403  0.198957  0.164164  0.342476  0.252817  0.149484   
4     0.223533  0.225579  0.242984  0.324876  0.206562  0.195979  0.205064   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.156945  0.205850  0.370043  0.231773  0.192334  0.112812  0.360882   
9218  0.130139  0.204997  0.443050  0.199473  0.152481  0.076325  0.434406   
9219  0.126670  0.201049  0.440742  0.202422  0.155786  0.080272  0.427547   
9220  0.120325  0.201472  0.438288  0.200345  0.159896  0.081591  0.434062   
9221  0.125274  0.206255  0.440225  0.198783  0.154737  0.077122  0.434784   

            14        15 is it leading df1 classificator  
0     0.176734  0.324807            no           leading  
1     0.220141  0.320237            no           leading  
2     0.203830  0.384769       leading                no  
3     0.165668  0.432032       leading                no  
4     0.250957  0.347999       leading                no  
...        ...       ...           ...               ...  
9217  0.301728  0.224578            no           leading  
9218  0.307077  0.182192            no           leading  
9219  0.308850  0.183331            no           leading  
9220  0.304462  0.179885            no           leading  
9221  0.302265  0.185829            no           leading  

[9222 rows x 18 columns]

In [107]:
df1

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading df2 classificator  
0     0.218948  0.353708       leading                no  
1     0.239259  0.313376       leading                no  
2     0.220283  0.386160            no           leading  
3     0.208863  0.398422            no           leading  
4     0.255678  0.342025            no           leading  
...        ...       ...           ...               ...  
9217  0.326239  0.204810       leading                no  
9218  0.336800  0.182580       leading                no  
9219  0.340207  0.181006       leading                no  
9220  0.337675  0.181289       leading                no  
9221  0.331585  0.185893       leading                no  

[9222 rows x 18 columns]

In [108]:
df1[(df1['is it leading']=='leading') & (df1['df2 classificator']=='leading')]

0         1         2         3         4         5         6  \
35    0.493512  0.098916  0.129751  0.277820  0.430239  0.163424  0.069483   
36    0.435730  0.080408  0.172848  0.311014  0.355670  0.157451  0.075914   
42    0.375222  0.125710  0.170236  0.328831  0.365359  0.176370  0.079085   
43    0.278027  0.226457  0.278027  0.217489  0.238710  0.200000  0.283871   
48    0.490305  0.124654  0.135734  0.249307  0.496000  0.128000  0.120000   
...        ...       ...       ...       ...       ...       ...       ...   
9176  0.292261  0.197867  0.250036  0.259836  0.260677  0.227539  0.295529   
9186  0.269423  0.214633  0.243267  0.272677  0.228806  0.237112  0.337532   
9193  0.217210  0.227779  0.265725  0.289285  0.180519  0.242811  0.416014   
9198  0.351861  0.176665  0.200665  0.270809  0.327310  0.183551  0.216474   
9216  0.179703  0.307464  0.269957  0.242876  0.157179  0.211269  0.496718   

             7         8         9        10        11        12        13  \
35    0.336854  0.423937  0.206376  0.162192  0.207494  0.393006  0.107324   
36    0.410965  0.382428  0.188115  0.162231  0.267226  0.333129  0.109208   
42    0.379186  0.312011  0.206906  0.194122  0.286961  0.331070  0.133001   
43    0.277419  0.249035  0.283784  0.231660  0.235521  0.160853  0.238372   
48    0.256000  0.433566  0.083916  0.202797  0.279720  0.265217  0.226087   
...        ...       ...       ...       ...       ...       ...       ...   
9176  0.216255  0.228590  0.313055  0.244648  0.213708  0.193590  0.237529   
9186  0.196550  0.215162  0.343092  0.259379  0.182367  0.170610  0.250621   
9193  0.160657  0.234569  0.355347  0.264145  0.145938  0.103796  0.373888   
9198  0.272665  0.218125  0.302596  0.197951  0.281328  0.277819  0.133879   
9216  0.134834  0.201244  0.413473  0.234405  0.150878  0.075757  0.393646   

            14        15 is it leading df2 classificator  
35    0.115021  0.384649       leading           leading  
36    0.139951  0.417712       leading           leading  
42    0.164169  0.371760       leading           leading  
43    0.275194  0.325581       leading           leading  
48    0.217391  0.291304       leading           leading  
...        ...       ...           ...               ...  
9176  0.287413  0.281468       leading           leading  
9186  0.309779  0.268990       leading           leading  
9193  0.297825  0.224491       leading           leading  
9198  0.232693  0.355609       leading           leading  
9216  0.347417  0.183180       leading           leading  

[1171 rows x 18 columns]

In [109]:
df1[(df1['is it leading']=='no') & (df1['df2 classificator']=='no')]

0         1         2         3         4         5         6  \
6     0.297059  0.218209  0.214272  0.270461  0.270065  0.221859  0.304784   
11    0.324721  0.137238  0.269610  0.268430  0.284279  0.197418  0.162246   
12    0.442911  0.098024  0.194793  0.264272  0.434731  0.129947  0.106320   
13    0.442179  0.100936  0.181818  0.275067  0.425452  0.135371  0.100437   
14    0.444733  0.096759  0.185900  0.272609  0.415038  0.144464  0.106572   
...        ...       ...       ...       ...       ...       ...       ...   
9144  0.401982  0.134218  0.166990  0.296810  0.335744  0.208971  0.171336   
9149  0.239223  0.230946  0.286815  0.243016  0.225510  0.252496  0.316182   
9180  0.468301  0.080310  0.163480  0.287908  0.369396  0.126714  0.032234   
9182  0.423108  0.093970  0.176253  0.306668  0.410798  0.152217  0.019672   
9190  0.206687  0.240640  0.260919  0.291754  0.162955  0.237346  0.458036   

             7         8         9        10        11        12        13  \
6     0.203291  0.226893  0.316493  0.238608  0.218006  0.184477  0.226417   
11    0.356056  0.340836  0.199131  0.225133  0.234900  0.224804  0.212130   
12    0.329002  0.414270  0.166727  0.175464  0.243538  0.352892  0.082019   
13    0.338740  0.408300  0.160079  0.181818  0.249802  0.349558  0.081198   
14    0.333925  0.401214  0.160030  0.181267  0.257490  0.348162  0.088972   
...        ...       ...       ...       ...       ...       ...       ...   
9144  0.283949  0.344882  0.194242  0.224893  0.235983  0.228726  0.183810   
9149  0.205811  0.225598  0.289108  0.273998  0.211296  0.138043  0.285086   
9180  0.471656  0.491043  0.111851  0.181213  0.215893  0.356592  0.093773   
9182  0.417314  0.414436  0.148699  0.177534  0.259331  0.325320  0.126696   
9190  0.141663  0.209670  0.400298  0.256465  0.133567  0.086614  0.386911   

            14        15 is it leading df2 classificator  
6     0.296310  0.292796            no                no  
11    0.213385  0.349681            no                no  
12    0.177497  0.387592            no                no  
13    0.177041  0.392203            no                no  
14    0.173977  0.388889            no                no  
...        ...       ...           ...               ...  
9144  0.189304  0.398160            no                no  
9149  0.311355  0.265515            no                no  
9180  0.156253  0.393382            no                no  
9182  0.150405  0.397579            no                no  
9190  0.316806  0.209670            no                no  

[1087 rows x 18 columns]

In [110]:
df1[(df1['is it leading']=='leading') & (df1['df2 classificator']=='no')]

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
5     0.399826  0.203989  0.193963  0.202221  0.325573  0.229391  0.171073   
7     0.239818  0.239306  0.267537  0.253339  0.213032  0.244597  0.351746   
9     0.368809  0.196246  0.258882  0.176063  0.219588  0.262344  0.194331   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
5     0.273964  0.271736  0.222691  0.224821  0.280752  0.242408  0.149479   
7     0.190625  0.246520  0.343069  0.242191  0.168221  0.116588  0.341132   
9     0.323738  0.333125  0.159231  0.270892  0.236751  0.241213  0.242106   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading df2 classificator  
0     0.218948  0.353708       leading                no  
1     0.239259  0.313376       leading                no  
5     0.224771  0.383342       leading                no  
7     0.303092  0.239188       leading                no  
9     0.161927  0.354754       leading                no  
...        ...       ...           ...               ...  
9217  0.326239  0.204810       leading                no  
9218  0.336800  0.182580       leading                no  
9219  0.340207  0.181006       leading                no  
9220  0.337675  0.181289       leading                no  
9221  0.331585  0.185893       leading                no  

[5385 rows x 18 columns]

In [111]:
df1[(df1['is it leading']=='no') & (df1['df2 classificator']=='leading')]

0         1         2         3         4         5         6  \
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
8     0.416845  0.124374  0.194637  0.264145  0.301473  0.214080  0.186119   
19    0.500442  0.044515  0.164989  0.290055  0.603922  0.023529  0.021569   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.460966  0.084138  0.200000  0.254897  0.503439  0.126547  0.063274   
9183  0.464567  0.059055  0.209974  0.266404  0.510490  0.132867  0.020979   
9184  0.422332  0.095618  0.183542  0.298508  0.413517  0.151354  0.027141   
9187  0.291577  0.221565  0.240962  0.245896  0.255964  0.250494  0.288413   
9201  0.391896  0.091329  0.180945  0.335830  0.470678  0.126285  0.060503   

             7         8         9        10        11        12        13  \
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
8     0.298328  0.273015  0.288232  0.235089  0.203664  0.222961  0.162274   
19    0.350980  0.234622  0.010343  0.202504  0.552531  0.491302  0.053362   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.306740  0.521947  0.129290  0.150838  0.197925  0.423199  0.076121   
9183  0.335664  0.485531  0.138264  0.189711  0.186495  0.426914  0.083527   
9184  0.407988  0.418421  0.144343  0.183777  0.253460  0.332822  0.122222   
9187  0.205129  0.238840  0.301940  0.263100  0.196120  0.176203  0.248187   
9201  0.342533  0.399279  0.147656  0.190592  0.262473  0.349976  0.106208   

            14        15 is it leading df2 classificator  
2     0.220283  0.386160            no           leading  
3     0.208863  0.398422            no           leading  
4     0.255678  0.342025            no           leading  
8     0.194534  0.420232            no           leading  
19    0.122238  0.333098            no           leading  
...        ...       ...           ...               ...  
9181  0.133213  0.367467            no           leading  
9183  0.208817  0.280742            no           leading  
9184  0.160284  0.384672            no           leading  
9187  0.321706  0.253904            no           leading  
9201  0.189409  0.354407            no           leading  

[1579 rows x 18 columns]

# organize P1 e P2 and save correct datasets

In [116]:
# in df1 table, get the values that went right and desconsider the rest
df1_leading = df1[(df1['is it leading']=='leading') & (df1['df2 classificator']=='no')]
df1_leading

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
5     0.399826  0.203989  0.193963  0.202221  0.325573  0.229391  0.171073   
7     0.239818  0.239306  0.267537  0.253339  0.213032  0.244597  0.351746   
9     0.368809  0.196246  0.258882  0.176063  0.219588  0.262344  0.194331   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.208206  0.295122  0.252995  0.243678  0.194308  0.221671  0.436505   
9218  0.187309  0.305090  0.279278  0.228323  0.151252  0.198895  0.515309   
9219  0.182440  0.308793  0.269244  0.239523  0.155995  0.203883  0.510171   
9220  0.178412  0.318684  0.257102  0.245802  0.153285  0.199025  0.526943   
9221  0.193269  0.306484  0.266413  0.233833  0.151770  0.198705  0.520735   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
5     0.273964  0.271736  0.222691  0.224821  0.280752  0.242408  0.149479   
7     0.190625  0.246520  0.343069  0.242191  0.168221  0.116588  0.341132   
9     0.323738  0.333125  0.159231  0.270892  0.236751  0.241213  0.242106   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.147517  0.225800  0.360937  0.237707  0.175555  0.105140  0.363812   
9218  0.134544  0.203061  0.414574  0.228123  0.154242  0.078054  0.402565   
9219  0.129952  0.200996  0.417262  0.229149  0.152593  0.078692  0.400095   
9220  0.120747  0.203126  0.412596  0.224698  0.159580  0.079292  0.401743   
9221  0.128790  0.205566  0.408780  0.225093  0.160562  0.080768  0.401753   

            14        15 is it leading df2 classificator  
0     0.218948  0.353708       leading                no  
1     0.239259  0.313376       leading                no  
5     0.224771  0.383342       leading                no  
7     0.303092  0.239188       leading                no  
9     0.161927  0.354754       leading                no  
...        ...       ...           ...               ...  
9217  0.326239  0.204810       leading                no  
9218  0.336800  0.182580       leading                no  
9219  0.340207  0.181006       leading                no  
9220  0.337675  0.181289       leading                no  
9221  0.331585  0.185893       leading                no  

[5385 rows x 18 columns]

In [119]:
# get the values that went right in df2. 
df2_leading = df2[(df2['is it leading']=='leading') & (df2['df1 classificator']=='no')]
df2_leading

0         1         2         3         4         5         6  \
2     0.390224  0.169756  0.146904  0.293116  0.350484  0.198594  0.199835   
3     0.422516  0.146274  0.156172  0.275037  0.405465  0.165853  0.059420   
4     0.344484  0.189148  0.202895  0.263473  0.274323  0.324033  0.178111   
8     0.417185  0.138139  0.178296  0.266380  0.288472  0.235663  0.173550   
19    0.495935  0.094026  0.117002  0.293036  0.388079  0.178808  0.078146   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.448299  0.099769  0.146680  0.305253  0.407002  0.175055  0.047046   
9183  0.431373  0.074272  0.207368  0.286988  0.486911  0.136126  0.031414   
9184  0.397670  0.110229  0.147543  0.344558  0.355090  0.177437  0.014306   
9187  0.278069  0.219681  0.224428  0.277822  0.278799  0.241243  0.255140   
9201  0.347779  0.139305  0.113118  0.399798  0.356435  0.195432  0.037608   

             7         8         9        10        11        12        13  \
2     0.251086  0.270882  0.285281  0.184960  0.258877  0.236150  0.175250   
3     0.369262  0.294403  0.198957  0.164164  0.342476  0.252817  0.149484   
4     0.223533  0.225579  0.242984  0.324876  0.206562  0.195979  0.205064   
8     0.302314  0.250616  0.324742  0.219052  0.205590  0.221485  0.180603   
19    0.354967  0.387597  0.166667  0.158915  0.286822  0.386079  0.104872   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.370897  0.368313  0.167695  0.165638  0.298354  0.330053  0.101582   
9183  0.345550  0.433718  0.118156  0.204611  0.243516  0.433858  0.114709   
9184  0.453168  0.363188  0.182199  0.152833  0.301780  0.291016  0.157981   
9187  0.224819  0.225789  0.310655  0.240702  0.222854  0.180240  0.260918   
9201  0.410525  0.305363  0.239072  0.120180  0.335386  0.294095  0.183028   

            14        15 is it leading df1 classificator  
2     0.203830  0.384769       leading                no  
3     0.165668  0.432032       leading                no  
4     0.250957  0.347999       leading                no  
8     0.177911  0.420002       leading                no  
19    0.121114  0.387935       leading                no  
...        ...       ...           ...               ...  
9181  0.113884  0.454482       leading                no  
9183  0.176688  0.274746       leading                no  
9184  0.127375  0.423629       leading                no  
9187  0.268635  0.290208       leading                no  
9201  0.129708  0.393169       leading                no  

[1579 rows x 18 columns]

In [121]:
leadings = df1_leading.append(df2_leading)
leadings

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
5     0.399826  0.203989  0.193963  0.202221  0.325573  0.229391  0.171073   
7     0.239818  0.239306  0.267537  0.253339  0.213032  0.244597  0.351746   
9     0.368809  0.196246  0.258882  0.176063  0.219588  0.262344  0.194331   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.448299  0.099769  0.146680  0.305253  0.407002  0.175055  0.047046   
9183  0.431373  0.074272  0.207368  0.286988  0.486911  0.136126  0.031414   
9184  0.397670  0.110229  0.147543  0.344558  0.355090  0.177437  0.014306   
9187  0.278069  0.219681  0.224428  0.277822  0.278799  0.241243  0.255140   
9201  0.347779  0.139305  0.113118  0.399798  0.356435  0.195432  0.037608   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
5     0.273964  0.271736  0.222691  0.224821  0.280752  0.242408  0.149479   
7     0.190625  0.246520  0.343069  0.242191  0.168221  0.116588  0.341132   
9     0.323738  0.333125  0.159231  0.270892  0.236751  0.241213  0.242106   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.370897  0.368313  0.167695  0.165638  0.298354  0.330053  0.101582   
9183  0.345550  0.433718  0.118156  0.204611  0.243516  0.433858  0.114709   
9184  0.453168  0.363188  0.182199  0.152833  0.301780  0.291016  0.157981   
9187  0.224819  0.225789  0.310655  0.240702  0.222854  0.180240  0.260918   
9201  0.410525  0.305363  0.239072  0.120180  0.335386  0.294095  0.183028   

            14        15 is it leading df2 classificator df1 classificator  
0     0.218948  0.353708       leading                no               NaN  
1     0.239259  0.313376       leading                no               NaN  
5     0.224771  0.383342       leading                no               NaN  
7     0.303092  0.239188       leading                no               NaN  
9     0.161927  0.354754       leading                no               NaN  
...        ...       ...           ...               ...               ...  
9181  0.113884  0.454482       leading               NaN                no  
9183  0.176688  0.274746       leading               NaN                no  
9184  0.127375  0.423629       leading               NaN                no  
9187  0.268635  0.290208       leading               NaN                no  
9201  0.129708  0.393169       leading               NaN                no  

[6964 rows x 19 columns]

In [124]:
leadings = leadings.loc[:, leadings.columns!='df2 classificator']

In [125]:
leadings = leadings.loc[:, leadings.columns!='df1 classificator']
leadings

0         1         2         3         4         5         6  \
0     0.321137  0.129837  0.284629  0.264398  0.286724  0.183457  0.188889   
1     0.319181  0.195369  0.267221  0.218229  0.257934  0.220533  0.228152   
5     0.399826  0.203989  0.193963  0.202221  0.325573  0.229391  0.171073   
7     0.239818  0.239306  0.267537  0.253339  0.213032  0.244597  0.351746   
9     0.368809  0.196246  0.258882  0.176063  0.219588  0.262344  0.194331   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.448299  0.099769  0.146680  0.305253  0.407002  0.175055  0.047046   
9183  0.431373  0.074272  0.207368  0.286988  0.486911  0.136126  0.031414   
9184  0.397670  0.110229  0.147543  0.344558  0.355090  0.177437  0.014306   
9187  0.278069  0.219681  0.224428  0.277822  0.278799  0.241243  0.255140   
9201  0.347779  0.139305  0.113118  0.399798  0.356435  0.195432  0.037608   

             7         8         9        10        11        12        13  \
0     0.340929  0.334607  0.205829  0.229560  0.230004  0.219631  0.207712   
1     0.293380  0.377825  0.152565  0.243996  0.225614  0.133936  0.313429   
5     0.273964  0.271736  0.222691  0.224821  0.280752  0.242408  0.149479   
7     0.190625  0.246520  0.343069  0.242191  0.168221  0.116588  0.341132   
9     0.323738  0.333125  0.159231  0.270892  0.236751  0.241213  0.242106   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.370897  0.368313  0.167695  0.165638  0.298354  0.330053  0.101582   
9183  0.345550  0.433718  0.118156  0.204611  0.243516  0.433858  0.114709   
9184  0.453168  0.363188  0.182199  0.152833  0.301780  0.291016  0.157981   
9187  0.224819  0.225789  0.310655  0.240702  0.222854  0.180240  0.260918   
9201  0.410525  0.305363  0.239072  0.120180  0.335386  0.294095  0.183028   

            14        15 is it leading  
0     0.218948  0.353708       leading  
1     0.239259  0.313376       leading  
5     0.224771  0.383342       leading  
7     0.303092  0.239188       leading  
9     0.161927  0.354754       leading  
...        ...       ...           ...  
9181  0.113884  0.454482       leading  
9183  0.176688  0.274746       leading  
9184  0.127375  0.423629       leading  
9187  0.268635  0.290208       leading  
9201  0.129708  0.393169       leading  

[6964 rows x 17 columns]

In [128]:
df1_not_leading = df1[(df1['is it leading']=='no') & (df1['df2 classificator']=='leading')]
df1_not_leading

0         1         2         3         4         5         6  \
2     0.384895  0.156670  0.163763  0.294673  0.343357  0.189627  0.213222   
3     0.420605  0.156624  0.179222  0.243548  0.392893  0.196070  0.063879   
4     0.347621  0.186882  0.204680  0.260816  0.276402  0.326196  0.179280   
8     0.416845  0.124374  0.194637  0.264145  0.301473  0.214080  0.186119   
19    0.500442  0.044515  0.164989  0.290055  0.603922  0.023529  0.021569   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.460966  0.084138  0.200000  0.254897  0.503439  0.126547  0.063274   
9183  0.464567  0.059055  0.209974  0.266404  0.510490  0.132867  0.020979   
9184  0.422332  0.095618  0.183542  0.298508  0.413517  0.151354  0.027141   
9187  0.291577  0.221565  0.240962  0.245896  0.255964  0.250494  0.288413   
9201  0.391896  0.091329  0.180945  0.335830  0.470678  0.126285  0.060503   

             7         8         9        10        11        12        13  \
2     0.253794  0.270963  0.266712  0.196314  0.266012  0.231923  0.161634   
3     0.347158  0.326489  0.179544  0.189743  0.304225  0.265516  0.127199   
4     0.218122  0.231967  0.242786  0.323287  0.201960  0.198065  0.204232   
8     0.298328  0.273015  0.288232  0.235089  0.203664  0.222961  0.162274   
19    0.350980  0.234622  0.010343  0.202504  0.552531  0.491302  0.053362   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.306740  0.521947  0.129290  0.150838  0.197925  0.423199  0.076121   
9183  0.335664  0.485531  0.138264  0.189711  0.186495  0.426914  0.083527   
9184  0.407988  0.418421  0.144343  0.183777  0.253460  0.332822  0.122222   
9187  0.205129  0.238840  0.301940  0.263100  0.196120  0.176203  0.248187   
9201  0.342533  0.399279  0.147656  0.190592  0.262473  0.349976  0.106208   

            14        15 is it leading df2 classificator  
2     0.220283  0.386160            no           leading  
3     0.208863  0.398422            no           leading  
4     0.255678  0.342025            no           leading  
8     0.194534  0.420232            no           leading  
19    0.122238  0.333098            no           leading  
...        ...       ...           ...               ...  
9181  0.133213  0.367467            no           leading  
9183  0.208817  0.280742            no           leading  
9184  0.160284  0.384672            no           leading  
9187  0.321706  0.253904            no           leading  
9201  0.189409  0.354407            no           leading  

[1579 rows x 18 columns]

In [129]:
df2_not_leading = df2[(df2['is it leading']=='no') & (df2['df1 classificator']=='leading')]
df2_not_leading

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
5     0.390219  0.203359  0.190421  0.216001  0.325709  0.220705  0.157059   
7     0.245384  0.246231  0.253724  0.254661  0.212776  0.248556  0.347474   
9     0.363176  0.192331  0.255318  0.189175  0.208188  0.268960  0.187910   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.217677  0.277106  0.258102  0.247115  0.198807  0.240962  0.403286   
9218  0.177678  0.325315  0.271782  0.225224  0.157297  0.227732  0.484832   
9219  0.184497  0.321992  0.257124  0.236388  0.162682  0.230316  0.480332   
9220  0.180791  0.338953  0.239285  0.240971  0.160620  0.226067  0.492988   
9221  0.182450  0.332885  0.256802  0.227862  0.155849  0.224191  0.494686   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
5     0.296526  0.225770  0.231365  0.224225  0.318640  0.229714  0.169079   
7     0.191194  0.239418  0.351044  0.245499  0.164039  0.111865  0.344876   
9     0.334941  0.317024  0.164201  0.269095  0.249680  0.230685  0.243200   
...        ...       ...       ...       ...       ...       ...       ...   
9217  0.156945  0.205850  0.370043  0.231773  0.192334  0.112812  0.360882   
9218  0.130139  0.204997  0.443050  0.199473  0.152481  0.076325  0.434406   
9219  0.126670  0.201049  0.440742  0.202422  0.155786  0.080272  0.427547   
9220  0.120325  0.201472  0.438288  0.200345  0.159896  0.081591  0.434062   
9221  0.125274  0.206255  0.440225  0.198783  0.154737  0.077122  0.434784   

            14        15 is it leading df1 classificator  
0     0.176734  0.324807            no           leading  
1     0.220141  0.320237            no           leading  
5     0.210109  0.391097            no           leading  
7     0.296237  0.247022            no           leading  
9     0.161882  0.364233            no           leading  
...        ...       ...           ...               ...  
9217  0.301728  0.224578            no           leading  
9218  0.307077  0.182192            no           leading  
9219  0.308850  0.183331            no           leading  
9220  0.304462  0.179885            no           leading  
9221  0.302265  0.185829            no           leading  

[5385 rows x 18 columns]

In [130]:
not_leadings = df2_not_leading.append(df1_not_leading)
not_leadings

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
5     0.390219  0.203359  0.190421  0.216001  0.325709  0.220705  0.157059   
7     0.245384  0.246231  0.253724  0.254661  0.212776  0.248556  0.347474   
9     0.363176  0.192331  0.255318  0.189175  0.208188  0.268960  0.187910   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.460966  0.084138  0.200000  0.254897  0.503439  0.126547  0.063274   
9183  0.464567  0.059055  0.209974  0.266404  0.510490  0.132867  0.020979   
9184  0.422332  0.095618  0.183542  0.298508  0.413517  0.151354  0.027141   
9187  0.291577  0.221565  0.240962  0.245896  0.255964  0.250494  0.288413   
9201  0.391896  0.091329  0.180945  0.335830  0.470678  0.126285  0.060503   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
5     0.296526  0.225770  0.231365  0.224225  0.318640  0.229714  0.169079   
7     0.191194  0.239418  0.351044  0.245499  0.164039  0.111865  0.344876   
9     0.334941  0.317024  0.164201  0.269095  0.249680  0.230685  0.243200   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.306740  0.521947  0.129290  0.150838  0.197925  0.423199  0.076121   
9183  0.335664  0.485531  0.138264  0.189711  0.186495  0.426914  0.083527   
9184  0.407988  0.418421  0.144343  0.183777  0.253460  0.332822  0.122222   
9187  0.205129  0.238840  0.301940  0.263100  0.196120  0.176203  0.248187   
9201  0.342533  0.399279  0.147656  0.190592  0.262473  0.349976  0.106208   

            14        15 is it leading df1 classificator df2 classificator  
0     0.176734  0.324807            no           leading               NaN  
1     0.220141  0.320237            no           leading               NaN  
5     0.210109  0.391097            no           leading               NaN  
7     0.296237  0.247022            no           leading               NaN  
9     0.161882  0.364233            no           leading               NaN  
...        ...       ...           ...               ...               ...  
9181  0.133213  0.367467            no               NaN           leading  
9183  0.208817  0.280742            no               NaN           leading  
9184  0.160284  0.384672            no               NaN           leading  
9187  0.321706  0.253904            no               NaN           leading  
9201  0.189409  0.354407            no               NaN           leading  

[6964 rows x 19 columns]

In [131]:
not_leadings = not_leadings.loc[:, not_leadings.columns!='df1 classificator']
not_leadings

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
5     0.390219  0.203359  0.190421  0.216001  0.325709  0.220705  0.157059   
7     0.245384  0.246231  0.253724  0.254661  0.212776  0.248556  0.347474   
9     0.363176  0.192331  0.255318  0.189175  0.208188  0.268960  0.187910   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.460966  0.084138  0.200000  0.254897  0.503439  0.126547  0.063274   
9183  0.464567  0.059055  0.209974  0.266404  0.510490  0.132867  0.020979   
9184  0.422332  0.095618  0.183542  0.298508  0.413517  0.151354  0.027141   
9187  0.291577  0.221565  0.240962  0.245896  0.255964  0.250494  0.288413   
9201  0.391896  0.091329  0.180945  0.335830  0.470678  0.126285  0.060503   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
5     0.296526  0.225770  0.231365  0.224225  0.318640  0.229714  0.169079   
7     0.191194  0.239418  0.351044  0.245499  0.164039  0.111865  0.344876   
9     0.334941  0.317024  0.164201  0.269095  0.249680  0.230685  0.243200   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.306740  0.521947  0.129290  0.150838  0.197925  0.423199  0.076121   
9183  0.335664  0.485531  0.138264  0.189711  0.186495  0.426914  0.083527   
9184  0.407988  0.418421  0.144343  0.183777  0.253460  0.332822  0.122222   
9187  0.205129  0.238840  0.301940  0.263100  0.196120  0.176203  0.248187   
9201  0.342533  0.399279  0.147656  0.190592  0.262473  0.349976  0.106208   

            14        15 is it leading df2 classificator  
0     0.176734  0.324807            no               NaN  
1     0.220141  0.320237            no               NaN  
5     0.210109  0.391097            no               NaN  
7     0.296237  0.247022            no               NaN  
9     0.161882  0.364233            no               NaN  
...        ...       ...           ...               ...  
9181  0.133213  0.367467            no           leading  
9183  0.208817  0.280742            no           leading  
9184  0.160284  0.384672            no           leading  
9187  0.321706  0.253904            no           leading  
9201  0.189409  0.354407            no           leading  

[6964 rows x 18 columns]

In [132]:
not_leadings = not_leadings.loc[:, not_leadings.columns!='df2 classificator']
not_leadings

0         1         2         3         4         5         6  \
0     0.358242  0.182401  0.203805  0.255553  0.280322  0.226452  0.144286   
1     0.320226  0.201471  0.252032  0.226270  0.260640  0.228051  0.209217   
5     0.390219  0.203359  0.190421  0.216001  0.325709  0.220705  0.157059   
7     0.245384  0.246231  0.253724  0.254661  0.212776  0.248556  0.347474   
9     0.363176  0.192331  0.255318  0.189175  0.208188  0.268960  0.187910   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.460966  0.084138  0.200000  0.254897  0.503439  0.126547  0.063274   
9183  0.464567  0.059055  0.209974  0.266404  0.510490  0.132867  0.020979   
9184  0.422332  0.095618  0.183542  0.298508  0.413517  0.151354  0.027141   
9187  0.291577  0.221565  0.240962  0.245896  0.255964  0.250494  0.288413   
9201  0.391896  0.091329  0.180945  0.335830  0.470678  0.126285  0.060503   

             7         8         9        10        11        12        13  \
0     0.348941  0.341426  0.265870  0.184048  0.208656  0.230901  0.267558   
1     0.302093  0.375664  0.159231  0.228165  0.236940  0.134228  0.325394   
5     0.296526  0.225770  0.231365  0.224225  0.318640  0.229714  0.169079   
7     0.191194  0.239418  0.351044  0.245499  0.164039  0.111865  0.344876   
9     0.334941  0.317024  0.164201  0.269095  0.249680  0.230685  0.243200   
...        ...       ...       ...       ...       ...       ...       ...   
9181  0.306740  0.521947  0.129290  0.150838  0.197925  0.423199  0.076121   
9183  0.335664  0.485531  0.138264  0.189711  0.186495  0.426914  0.083527   
9184  0.407988  0.418421  0.144343  0.183777  0.253460  0.332822  0.122222   
9187  0.205129  0.238840  0.301940  0.263100  0.196120  0.176203  0.248187   
9201  0.342533  0.399279  0.147656  0.190592  0.262473  0.349976  0.106208   

            14        15 is it leading  
0     0.176734  0.324807            no  
1     0.220141  0.320237            no  
5     0.210109  0.391097            no  
7     0.296237  0.247022            no  
9     0.161882  0.364233            no  
...        ...       ...           ...  
9181  0.133213  0.367467            no  
9183  0.208817  0.280742            no  
9184  0.160284  0.384672            no  
9187  0.321706  0.253904            no  
9201  0.189409  0.354407            no  

[6964 rows x 17 columns]

In [133]:
leadings.to_csv('P1.csv')

In [134]:
not_leadings.to_csv('P2.csv')