In [1]:
import pandas as pd
import numpy as np

#graphic packages
import matplotlib.pyplot as plt
import seaborn as sns                                   

# encode the columns we dont want to predict
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder         

# encode the column we want to predict
from sklearn.preprocessing import LabelEncoder          

# split in test & train datasets
from sklearn.model_selection import train_test_split    

# feature scaling
from sklearn.preprocessing import StandardScaler

# Organize the dataframes

In [2]:
path = "C:/Users/Bruna/OneDrive/Documentos/estudos sobre DNA/"

file1="df1_classificada.csv"
df1=pd.read_csv(path+file1,sep=',')

file2="df2_classificada.csv"
df2=pd.read_csv(path+file2,sep=',')

In [3]:
df1 = df1.loc[:, df2.columns!='Unnamed: 0']

In [4]:
df2 = df2.loc[:, df2.columns!='Unnamed: 0']

# Filter the DNA strand with one leading and the other not leading

In [5]:
df1.rename(columns={'is it leading':'leading df1'},inplace=True)

In [6]:
df2.rename(columns={'is it leading':'leading df2'},inplace=True)

In [7]:
df = df1.copy()

In [8]:
df['0d']=df2['0']
df['1d']=df2['1']
df['2d']=df2['2']
df['3d']=df2['3']
df['4d']=df2['4']
df['5d']=df2['5']
df['6d']=df2['6']
df['7d']=df2['7']
df['8d']=df2['8']
df['9d']=df2['9']
df['10d']=df2['10']
df['11d']=df2['11']
df['12d']=df2['12']
df['13d']=df2['13']
df['14d']=df2['14']
df['15d']=df2['15']
df['leading df2']=df2['leading df2']

In [9]:
leading1=df[(df['leading df1']=='leading') & (df['leading df2']=='no')]

In [10]:
leading2=df[(df['leading df1']=='no') & (df['leading df2']=='leading')]

In [11]:
leadings = leading1.append(leading2)

# Append the strands and name each part of the DNA

we want one single dataframe, with half been the first half of a DNA and the second part being the second part of the correspondind DNA. They are such that half of the DNA is leading and the other half is not.

In [12]:
data1 = leadings.loc[:,'0':'leading df1']

In [13]:
data2 = leadings.loc[:,'0d':'leading df2']

In [14]:
data1.rename(columns={'leading df1':'leading'}, inplace=True)

In [15]:
data2.rename(columns={'0d':'0', '1d':'1', '2d':'2', '3d':'3', '4d':'4', '5d':'5'},inplace=True)

In [16]:
data2.rename(columns={'6d':'6', '7d':'7', '8d':'8', '9d':'9', '10d':'10', '11d':'11'},inplace=True)

In [17]:
data2.rename(columns={'12d':'12', '13d':'13', '14d':'14', '15d':'15', 'leading df2':'leading'},inplace=True)

In [18]:
data1['DNA']= 'p1'   # we need this for the ML to know they are each half of a DNA strand
data2['DNA']= 'p2'

In [19]:
data = data1.append(data2)

In [20]:
new_columns=['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','DNA','leading']
data=data.reindex(columns=new_columns)

# data preprocessing

In [21]:
X=data.iloc[:, :-1].values     #### all the columns except the one we want to predict
y=data.iloc[:, -1].values      #### the column we want to predict

# Encode DNA column

In [22]:
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [16])],remainder='passthrough') # function to encode p1 & p2
X = np.array(ct.fit_transform(X))                     # call it for the set we want to train the model on 

In [23]:
le=LabelEncoder()
y=le.fit_transform(y)                  # encode leading & no leading column

# Split train & test sets

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1)

In [110]:
X_train

array([[1.0, 0.0, 0.341430948419301, ..., 0.19624538242596698,
        0.2164113122994, 0.367528613819415],
       [0.0, 1.0, 0.17883987398767198, ..., 0.3363669943475819,
        0.39470702718809997, 0.17569367059532],
       [1.0, 0.0, 0.301450955505253, ..., 0.22364313348945397,
        0.295766407916852, 0.294654174840395],
       ...,
       [1.0, 0.0, 0.29476899748952, ..., 0.225942915018385,
        0.2970077723059311, 0.291980360065466],
       [1.0, 0.0, 0.28673351226163896, ..., 0.268147155397708,
        0.268862829189841, 0.298637003283522],
       [1.0, 0.0, 0.4108563250906911, ..., 0.12679719673434,
        0.16906292897911998, 0.39664764106639705]], dtype=object)

In [111]:
X_test

array([[0.0, 1.0, 0.3684853400301951, ..., 0.15265029830197302,
        0.138806027229616, 0.37870487226556504],
       [1.0, 0.0, 0.170786241688809, ..., 0.35006386708188,
        0.376971954425942, 0.17514964476849304],
       [1.0, 0.0, 0.246588693957115, ..., 0.266512166859791,
        0.3742757821552721, 0.20973348783314],
       ...,
       [1.0, 0.0, 0.341430948419301, ..., 0.19624051499131,
        0.216418678729963, 0.367524783653992],
       [1.0, 0.0, 0.39984038308060704, ..., 0.20579420579420604,
        0.15784215784215802, 0.34465534465534503],
       [1.0, 0.0, 0.369004979470604, ..., 0.21399261386951202,
        0.25410340582683605, 0.304472712351252]], dtype=object)

In [112]:
y_train

array([0, 1, 1, ..., 1, 0, 0])

In [113]:
y_test

array([1, 0, 0, ..., 0, 1, 0])

# Feature scaling

Is the distribution normal? If yes, we use Normalization as feature scaling instead of Standardisation. I'll test all the columns.

In [ ]:
sns.displot(data['0'])
plt.savefig('distribution column 0')
plt.show()

In [ ]:
sns.displot(data['1'])
plt.savefig('distribution column 1')
plt.show()

In [ ]:
sns.displot(data['2'])
plt.savefig('distribution column 2')
plt.show()

In [ ]:
sns.displot(data['3'])
plt.savefig('distribution column 3')
plt.show()

In [ ]:
sns.displot(data['4'])
plt.savefig('distribution column 4')
plt.show()

In [ ]:
sns.displot(data['5'])
plt.savefig('distribution column 5')
plt.show()

In [ ]:
sns.displot(data['6'])
plt.savefig('distribution column 6')
plt.show()

In [ ]:
sns.displot(data['7'])
plt.savefig('distribution column 7')
plt.show()

In [ ]:
sns.displot(data['8'])
plt.savefig('distribution column 8')
plt.show()

In [ ]:
sns.displot(data['9'])
plt.savefig('distribution column 9')
plt.show()

In [ ]:
sns.displot(data['10'])
plt.savefig('distribution column 10')
plt.show()

In [ ]:
sns.displot(data['11'])
plt.savefig('distribution column 11')
plt.show()

In [ ]:
sns.displot(data['12'])
plt.savefig('distribution column 12')
plt.show()

In [ ]:
sns.displot(data['13'])
plt.savefig('distribution column 13')
plt.show()

In [ ]:
sns.displot(data['14'])
plt.savefig('distribution column 14')
plt.show()

In [ ]:
sns.displot(data['15'])
plt.savefig('distribution column 15')
plt.show()

In [ ]:
sns.displot(data['DNA'])
plt.savefig('distribution column DNA')
plt.show()

In [ ]:
sns.displot(data['leading'])
plt.savefig('distribution column leading')
plt.show()

We do not apply scaling for the dummy variables (in this case columns "DNA" and "leading").

I've decided not to apply feauture scaling, because the data is already normalized. If the model turns out very bad I might reconsider.

# Machine Learning models

# K-NN Model

For when we want to split our data en K sets alike each other. This case is 2: either leading or not

In [114]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=2, metric='minkowski', p=2)     # euclidean distance
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [115]:
y_pred=classifier.predict(X_test)
y_pred, y_test

(array([1, 0, 0, ..., 0, 1, 0]), array([1, 0, 0, ..., 0, 1, 0]))

In [116]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[636,  87],
       [271, 399]], dtype=int64)

In [117]:
accuracy_score(y_test, y_pred)

0.7430007178750897

# Logistic regression

For when we want to predict binary values, it uses the probability of being closer to 1 than it is from 0 (or the opposite)

I believe this is not the best model because is alike a linear regression but with log(), our problem has too many variables to be linear

In [118]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [119]:
y_pred = classifier.predict(X_test)

In [120]:
# confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[574, 149],
       [136, 534]], dtype=int64)

In [121]:
accuracy_score(y_test, y_pred)

0.7954055994256999

# Support Vector Machine (SVM)

For linearly separable data, separate our data in 2 groups (in this case "leading" and "not leading") but I am not sure if it is linearly seperable

In [122]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [123]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [124]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[575 148]
 [134 536]]


0.797559224694903